<?php
/**
 * @file
 * Code for the BG Link feature.
 */

include_once 'bglink.features.inc';

/**
 * Implements hook_views_query_alter()
 */
function bglink_views_query_alter(&$view, &$query) {
  // Transform bgpage nid that comes as an argument into its parents field.
  if (($view->name === 'links') && ($view->current_display == 'by_bgpage')) {
    _bgpage_views_query_alter_for_field_parent($view, $query);
  }
}

/**
 * Implements hook_menu().
 */
function bglink_menu() {
  $items = array();

  $items['node/%bgpage_node/bglink/add'] = array(
    'title' => 'Add link',
    'page callback' => 'bglink_add_link',
    'page arguments' => array(1),
    'access arguments' => array('create bglink content'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'bglink.pages.inc',
  );

  return $items;
}
