<?php
/**
 * @file
 * Code for the BG Link feature.
 */

include_once 'bglink.features.inc';

/**
 * Implements hook_views_query_alter()
 */
function bglink_views_query_alter(&$view, &$query) {
  // Transform bgpage nid that comes as an argument into its parents field.
  if (($view->name === 'links') && ($view->current_display == 'by_bgpage')) {
    _bgpage_views_query_alter_for_field_parent($view, $query);
  }
}
