<?php
/**
 * @file
 * Code for the BG Search feature.
 */

include_once 'bgsearch.features.inc';

/**
 * Implements hook_node_insert().
 */
function bgsearch_node_insert($node) {
  if ($node->type == 'bgimage') {
    _bgsearch_update_bgpage_totals($node);
  }
}

/**
 * Implements hook_node_update().
 */
function bgsearch_node_update($node) {
  if ($node->type == 'bgimage') {
    _bgsearch_update_bgpage_totals($node);
  }
}

/**
 * Implements hook_node_delete().
 */
function bgsearch_node_delete($node) {
  if ($node->type == 'bgimage') {
    _bgsearch_update_bgpage_totals($node);
  }
}

/**
 * Marks bgpage parent nodes of a bgimage node to be reindexed.
 *
 * This is so the total amount of images under a bgpage is
 * recalculated when an image is created, unpublished or
 * deleted.
 *
 * @param $node
 *   A BGImage node.
 */
function _bgsearch_update_bgpage_totals($node) {
  if (!empty($node->field_parent[LANGUAGE_NONE][0]['value'])) {
    $nids = explode(',', $node->field_parent[LANGUAGE_NONE][0]['value']);
    $parent_nodes = node_load_multiple($nids);
    foreach ($parent_nodes as $parent) {
      apachesolr_entity_update($parent, 'node');
    }
  }
}

/**
 * Implements hook_menu_alter().
 */
function bgsearch_menu_alter(&$items) {
  // Disable apachesolr search menu items.
  unset($items['search/site']);
  unset($items['search/site/%']);
  // Set Search API as the default tab.
  $items['search/global']['type'] = MENU_DEFAULT_LOCAL_TASK;
  // Adjust the tab parent of the user search. This is so tabs are still visible
  //while searching users.
  unset($items['search/user/%menu_tail']['tab_root']);
  unset($items['search/user/%menu_tail']['tab_parent']);
  // Redirect "search" to "search/global".
  $items['search']['page callback'] = 'drupal_goto';
  $items['search']['page arguments'] = array('search/global');
}
