<?php
/**
 * @file
 * bgsearch.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function bgsearch_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['apachesolr_search-sort'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'sort',
    'module' => 'apachesolr_search',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-ViKOn605BjuPkX1yzKkaWyMbDhEXxcHM'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ViKOn605BjuPkX1yzKkaWyMbDhEXxcHM',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-X2BDj6C5Fi1XcRZsERPXwPcZ5ofa0UyQ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'X2BDj6C5Fi1XcRZsERPXwPcZ5ofa0UyQ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-ZPZ6jlY0Sz6S3514ybBjT0rWnv0eyNZK'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ZPZ6jlY0Sz6S3514ybBjT0rWnv0eyNZK',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Za8lWIXN16R0Cq79viEEG9l05qvmOSND'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Za8lWIXN16R0Cq79viEEG9l05qvmOSND',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-efolWGlFiunUWqnQd2V3My7YlY1bcnu7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'efolWGlFiunUWqnQd2V3My7YlY1bcnu7',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-eh4iUzi2Kip0kUqxRMqMx2DvmVkyWGke'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'eh4iUzi2Kip0kUqxRMqMx2DvmVkyWGke',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-i3ICruM04X5ExHUrITR0of4TXaLuqPFF'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'i3ICruM04X5ExHUrITR0of4TXaLuqPFF',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-iSe2skBAzWKWR1cegrNa9x4yjQuUJp1U'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'iSe2skBAzWKWR1cegrNa9x4yjQuUJp1U',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-lUDBVnsAAfFlmwsx0TtxJaug4iPrG037'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'lUDBVnsAAfFlmwsx0TtxJaug4iPrG037',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-lyo23R60GodYSMs5LehRKHq5RjS8bzU4'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'lyo23R60GodYSMs5LehRKHq5RjS8bzU4',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-syi3y0O9NvaGv7rFg6RcXIFqsTCbyPKe'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'syi3y0O9NvaGv7rFg6RcXIFqsTCbyPKe',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-vzaQkN37NCQtMDpfeRN0Lwif7GY57nZR'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'vzaQkN37NCQtMDpfeRN0Lwif7GY57nZR',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-y0D120Yl2rFozKNVyxnLx0dLFXpcVmRg'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'y0D120Yl2rFozKNVyxnLx0dLFXpcVmRg',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-yewPnlJeRl76eNaV7ok2cnlYXsZvK8Fh'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'yewPnlJeRl76eNaV7ok2cnlYXsZvK8Fh',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['search_api_page-bugguide_search'] = array(
    'cache' => 5,
    'custom' => 0,
    'delta' => 'bugguide_search',
    'module' => 'search_api_page',
    'node_types' => array(),
    'pages' => 'search
search/*',
    'roles' => array(),
    'themes' => array(
      'bulma' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bulma',
        'weight' => 0,
      ),
      'bulmabug' => array(
        'region' => 'navbar',
        'status' => 1,
        'theme' => 'bulmabug',
        'weight' => 0,
      ),
      'shiny' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'shiny',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  return $export;
}
