<?php
/**
 * @file
 * Code for the BG Image feature.
 */

include_once 'bgimage.features.inc';
include_once './images/image_obfuscate.inc';

/**
 * Implementation of hook_theme().
 */
function bgimage_theme() {
  $module_path = drupal_get_path('module', 'bgimage');
  return array(
    'views_view__featured_image__block' => array(
      'variables' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'template' => 'views-view--featured-image--block',
      'base hook' => 'views_view',
      'path' => $module_path . '/templates',
    )
  );
}

/**
 * Implements hook_menu_alter().
 */
function bgimage_menu_alter(&$items) {
  $items['node/%node/clone/%clone_token']['title callback'] = '_bgimage_clone_action_link_title';
}

/**
 * Implements hook_menu().
 */
function bgimage_menu() {
  $items = array();

  $items['bgimage/clip/%node'] = array(
    'title' => 'Adds an image to the Clipboard',
    'page callback' => 'bgimage_clip',
    'page arguments' => array(2),
    'access arguments' => array('use image clipboard'),
    'type' => MENU_CALLBACK,
    'file' => 'bgimage.pages.inc',
  );

  $items['bgimage/unclip/%node'] = array(
    'title' => 'Removes an image from the clipboard',
    'page callback' => 'bgimage_unclip',
    'page arguments' => array(2),
    'access arguments' => array('use image clipboard'),
    'type' => MENU_CALLBACK,
    'file' => 'bgimage.pages.inc',
  );

  $items['bgimage/move/%node'] = array(
    'title' => 'Moves images in the clipboard to the current page',
    'page callback' => 'bgimage_move_clipped',
    'page arguments' => array(2),
    'access arguments' => array('use image clipboard'),
    'type' => MENU_CALLBACK,
    'file' => 'bgimage.pages.inc',
  );

  $items['bgimage/quiet_move/%node'] = array(
    'title' => 'Quietly moves images in the clipboard to the current page',
    'page callback' => 'bgimage_move_clipped',
    'page arguments' => array(2, true),
    'access arguments' => array('quiet move all bgimages'),
    'type' => MENU_CALLBACK,
    'file' => 'bgimage.pages.inc',
  );

  $items['bgimage/link'] = array(
    'title' => 'Links images on the clipboard',
    'page callback' => 'bgimage_link_clipped',
    'access arguments' => array('use image clipboard'),
    'type' => MENU_CALLBACK,
    'file' => 'bgimage.pages.inc',
  );

  $items['bgimage/unlink'] = array(
    'title' => 'Unlinks a series of images',
    'page callback' => 'bgimage_unlink_image_series',
    'page arguments' => array(2),
    'access arguments' => array('use image clipboard'),
    'type' => MENU_CALLBACK,
    'file' => 'bgimage.pages.inc',
  );

  $items['bgimage/unclip_all'] = array(
    'title' => 'Removes images from the Clipboard',
    'page callback' => 'bgimage_unclip_all',
    'access arguments' => array('use image clipboard'),
    'type' => MENU_CALLBACK,
    'file' => 'bgimage.pages.inc',
  );

  $items['bgimage/stage'] = array(
    'title' => 'Set stage',
    'page callback' => 'bgimage_set_stage',
    'page arguments' => (array(2)),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['node/%bgpage_node/bgimage/add'] = array(
    'title' => 'Add image',
    'page callback' => 'bgimage_add_image',
    'page arguments' => array(1),
    'access arguments' => array('create bgimages'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'bgimage.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function bgimage_permission() {
  return array(
    'create bgimages' => array(
      'title' => 'Create bgimage nodes',
    ),
    'view fullsize bgimages' => array(
      'title' => 'View full size images',
    ),
    'use image clipboard' => array(
      'title' => 'Use image clipboard',
    ),
    'move all bgimages' => array(
      'title' => 'Move all bgimages',
    ),
    'quiet move all bgimages' => array(
      'title' => 'Quiet move all bgimages',
    ),
    'link all bgimages' => array(
      'title' => 'Link bgimage nodes',
    ),
  );
}

/**
 * Implements hook_apachesolr_index_document_build_node().
 */
function bgimage_apachesolr_index_document_build_node($document, $entity, $env_id) {
  if ($entity->type !== 'bgimage') {
    return;
  }

  // Internal image's identifier (so authors can search and find their images).
  if (!empty($entity->field_bgimage_id[LANGUAGE_NONE][0]['value'])) {
    $document->addField('ts_field_bgimage_id', $entity->field_bgimage_id[LANGUAGE_NONE][0]['value']);
  }

  // Parents field used for searching for descendants.
  $parents = array();
  if (!empty($entity->field_parent[LANGUAGE_NONE][0]['value'])) {
    $parents = explode(',', $entity->field_parent[LANGUAGE_NONE][0]['value']);
  }
  foreach ($parents as $parent) {
    $document->addField('sm_bgimage_parents', $parent);
  }

  // Immediate parent's nid and title used for grouping results.
  $parent_nid = bg_get_parent_nid($entity);
  if ($parent_nid != NULL) {
    $parent_node = node_load($parent_nid);
    if (!empty($parent_node)) {
      $document->addField('is_bgimage_immediate_parent', $parent_nid);
      $document->addField('ss_bgimage_immediate_parent_title', $parent_node->title);
    }
  }

  // List of parents as links, including current node. Used at the Images tab.
  $breadcrumbs = bg_create_taxonomic_breadcrumb($entity, 'Scientific name');
  foreach ($breadcrumbs as $breadcrumb) {
    $document->addField('sm_bgimage_breadcrumbs', $breadcrumb);
  }

  // Classification field used for sorting.
  $classification = '';
  if (!empty($entity->field_parent[LANGUAGE_NONE][0]['value'])) {
    $classification = $entity->field_parent[LANGUAGE_NONE][0]['value'] . ',';
  }
  $classification .= $entity->nid;
  $document->addField('ss_bgimage_classification', $classification);

  // Image thumbnail.
  $node_wrapper = entity_metadata_wrapper('node', $entity);
  $field_bgimage = $node_wrapper->field_bgimage_image->value();
  if (!empty($field_bgimage)) {
    $image_properties = array(
      'style_name' => 'bg_small',
      'path' => $field_bgimage['uri'],
      'alt' => $node_wrapper->title->value(array('sanitize' => TRUE)),
      'title' => $node_wrapper->title->value(array('sanitize' => TRUE)),
      'attributes' => array('style' => 'margin: 10px;'),
    );
    $image = theme('image_style', $image_properties);
    $link = '<a href="' . url('node/' . $entity->nid) . '" title="' . $node_wrapper->title->value(array('sanitize' => TRUE)) . '">' . $image . '</a>';
    $document->addField('ss_bgimage_thumbnail', $link);
  }

  // Rating field used for sorting.
  $rating_avg = 0;
  $rating_count = 0;
  // Rating cannot be accessed through an EMW :-(
  if (!empty($entity->field_bgimage_representative[LANGUAGE_NONE][0])) {
    $rating_avg = $entity->field_bgimage_representative[LANGUAGE_NONE][0]['average'];
    $rating_count = $entity->field_bgimage_representative[LANGUAGE_NONE][0]['count'];
  }
  $document->addField('is_bgimage_rating_avg', $rating_avg);
  $document->addField('is_bgimage_rating_count', $rating_count);
}

/**
 * Implements hook_apachesolr_field_name_map_alter().
 */
function bgimage_apachesolr_field_name_map_alter(&$map) {
  $map['ts_field_bgimage_id'] = t('Image ID (used by authors for private tagging)');
}

/**
 * Implements hook_ds_fields_info().
 */
function bgimage_ds_fields_info($entity_type) {
  $fields = array();

  if ($entity_type == 'node') {
    $fields['bgimage_clip'] = array(
      'title' => t('Add to clipboard'),
      'description' => t('Adds an image to the clipboard.'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => '_bgimage_field_clip',
      'file' => drupal_get_path('module', 'bgimage') . '/bgimage.ds.field.inc',
    );

    $fields['bgimage_photo_number'] = array(
      'title' => t('Photo number'),
      'description' => t('Renders photo number as Photo #123456.'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => '_bgimage_field_photo_number',
      'file' => drupal_get_path('module', 'bgimage') . '/bgimage.ds.field.inc',
    );

    $fields['bgimage_copyright'] = array(
      'title' => t('Photo copyright'),
      'description' => t('Renders a copyright statement.'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => '_bgimage_field_copyright',
      'file' => drupal_get_path('module', 'bgimage') . '/bgimage.ds.field.inc',
    );

    $fields['bgimage_related'] = array(
      'title' => t('Related images'),
      'description' => t('Renders related images for an specimen.'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => '_bgimage_field_related_images',
      'file' => drupal_get_path('module', 'bgimage') . '/bgimage.ds.field.inc',
    );

    $fields['bgimage_title_classification'] = array(
      'title' => t('Title and classification'),
      'description' => t('Renders the title and classification of an image.'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => '_bgimage_field_title_classification',
      'file' => drupal_get_path('module', 'bgimage') . '/bgimage.ds.field.inc',
    );

    $fields['bgimage_field_placed_by'] = array(
      'title' => t('Placed by'),
      'description' => t('Shows who uploaded an image.'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => '_bgimage_field_placed_by',
      'file' => drupal_get_path('module', 'bgimage') . '/bgimage.ds.field.inc',
    );

    $fields['bgimage_field_taxonomy_path'] = array(
      'title' => t('Taxonomy path'),
      'description' => t('Renders a list of taxonomy links for this image.'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => '_bgimage_field_taxonomy_path',
      'file' => drupal_get_path('module', 'bgimage') . '/bgimage.ds.field.inc',
    );

    return array($entity_type => $fields);
  }
  return;
}

/**
 * Implements hook_field_formatter_info().
 */
function bgimage_field_formatter_info() {
  $formatters = array(
    'bgimage_conditional_link_formatter' => array(
      'label' => t('Image Conditional Link'),
      'field types' => array('image'),
      'settings' => array('image_style' => 'bg_large', 'image_link' => ''),
    ),
  );

  return $formatters;
}

/**
 * Implements hook_field_formatter_view().
 */
function bgimage_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  // Check if the formatter involves a link.
  if ($display['settings']['image_link'] == 'content') {
    $uri = entity_uri($entity_type, $entity);
  }
  elseif ($entity->type == 'bgimage' && count($items) == 1) {
    // Provide a link to the fullsize image if either the user created the image
    // or they have the right permission.
    global $user;
    if ($items[0]['uid'] == $user->uid || user_access('view fullsize bgimages')) {
      $uri = array(
        'path' => file_create_url($items[0]['uri']),
        'options' => array(),
      );
    }
  }

  foreach ($items as $delta => $item) {
    $element[$delta] = array(
      '#theme' => 'image_formatter',
      '#item' => $item,
      '#image_style' => $display['settings']['image_style'],
      '#path' => isset($uri) ? $uri : '',
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_form() by wrapping the default.
 */
function bgimage_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  return image_field_formatter_settings_form($field, $instance, $view_mode, $form,$form_state);
}

/**
 * Implements hook_field_formatter_settings_summary() by wrapping the default.
 */
function bgimage_field_formatter_settings_summary($field, $instance, $view_mode) {
  return image_field_formatter_settings_summary($field, $instance, $view_mode);
}

/**
 * Implements hook_node_validate().
 */
function bgimage_node_validate($node, $form, &$form_state) {
  if ($node->type != 'bgimage') {
    return;
  }

  drupal_load('module', 'bg');

  // Attempt to set the full parent based on our calling nid.
  bg_node_validate_set_parent($form_state, arg(3));

  if ($node->{'field_bgimage_image'}[LANGUAGE_NONE][0]['fid'] == 0) {
    form_set_error('field_bgimage_image', 'Did you forget to attach an image? Please attach one and resubmit.');
  }

  if (strtotime($form_state['values']['field_bgimage_date'][LANGUAGE_NONE][0]['value']) > time()) {
    form_set_error('field_bgimage_date', 'The date taken cannot be in the future.');
  }

  //if ((strstr($node->parent, ",57,") && !$node->immature && !$node->adult)) {
	//  $error["leps_stage"] = theme("theme_error", "Please check adult (moth/butterfly) and/or immature (egg/caterpillar/pupa) when submitting to Lepidoptera.");
  //}

  $county = isset($node->{'field_bgimage_county'}[LANGUAGE_NONE][0]['value']) ? $node->{'field_bgimage_county'}[LANGUAGE_NONE][0]['value'] : '';
  if (bg_str_ends_with(strtoupper($county), ' PARISH')) {
     $node->{'field_bgimage_county'}[LANGUAGE_NONE][0]['value'] = substr($county, 0, strlen($county) - 7);
  }
  if (bg_str_ends_with(strtoupper($county), ' COUNTY')) {
     $node->{'field_bgimage_county'}[LANGUAGE_NONE][0]['value'] = substr($county, 0, strlen($county) - 7);
  }
  if (bg_str_ends_with(strtoupper($county), ' CO')) {
     $node->{'field_bgimage_county'}[LANGUAGE_NONE][0]['value'] = substr($county, 0, strlen($county) - 3);
  }
  if (bg_str_ends_with(strtoupper($county), ' CO.')) {
     $node->{'field_bgimage_county'}[LANGUAGE_NONE][0]['value'] = substr($county, 0, strlen($county) - 4);
  }
  if ((strtoupper($county) == 'USA') ||
		(strtoupper($county) == 'UNITED STATES') ||
		(strtoupper($county) == 'CANADA')) {
		form_set_error('field_bgimage_county', 'You have entered a country here. Please specify the county/parish/district/region instead.');
	}

	// TODO
	// bgimage_set_titles()
}

/**
 * Implements hook_node_insert().
 */
function bgimage_node_insert($node) {
  if ($node->type != 'bgimage') {
    return;
  }

  _bgimage_obfuscate_uploaded_image($node);

  // Mirror information to bgimage table for scalability.
  // Note that we are inside node_save()'s database transaction.
  $fields = _bgimage_prepare($node);
  $fields['base'] = $node->bgimage_uuid;
  $result = db_insert('bgimage')
    ->fields($fields)
    ->execute();

  // Update bgimage_series table used for rendering related images.
  if (isset($node->original_nid)) {
    $result = db_query('select * from {bgimage_series} where nid = :nid', array(
      ':nid' => $node->original_nid,
    ))->fetchObject();
    
    // The bgimage_series table is only used if there is more than one image.
    // If this is the second image initialize the series.
    if (!$result) {
      db_insert('bgimage_series')
        ->fields(array(
          'nid' => $node->original_nid,
          'weight' => 0,
          'series' => $node->original_nid,
        ))
        ->execute();
    }
    $max_weight = db_query('SELECT MAX(weight) FROM {bgimage_series} WHERE series = :nid', array(
      ':nid' => $node->original_nid,
    ))->fetchField();
    
    // Add the new image at the end of the series.
    db_insert('bgimage_series')
      ->fields(array(
        'nid' => $node->nid,
        'weight' => $max_weight + 1,
        'series' => $node->original_nid,
      ))
      ->execute();
  }
}

/**
 * Implements hook_node_update().
 */
function bgimage_node_update($node) {
  if ($node->type != 'bgimage') {
    return;
  }

  _bgimage_obfuscate_uploaded_image($node);

  // Mirror information to bgimage table for scalability.
  // Note that we are inside node_save()'s database transaction.
  $fields = _bgimage_prepare($node);
  $result = db_update('bgimage')
    ->fields($fields)
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Implements hook_node_delete().
 */
function bgimage_node_delete($node) {
  if ($node->type != 'bgimage') {
    return;
  }

  // Note that we are inside node_delete()'s database transaction.

  // Delete row from bgimage table.
  db_delete('bgimage')
    ->condition('nid', $node->nid)
    ->execute();

  // Update the series table if needed.
  $deleted_nid = $node->nid;
  $result = db_query('SELECT weight, series FROM {bgimage_series} WHERE nid = :nid', array(':nid' => $deleted_nid))->fetchAssoc();
  if (!$result) {
    return;
  }

  $series_base = $result['series'];
  $deleted_weight = $result['weight'];
  $series_nodes = db_query('SELECT nid, weight FROM {bgimage_series} WHERE series = :series', array(':series' => $series_base))->fetchAllAssoc('weight', PDO::FETCH_ASSOC);
  if (count($series_nodes) <= 2) {
    // There are only two images in the series and we're deleting one, so the
    // series record should be removed.
    db_delete('bgimage_series')
      ->condition('series', $series_base)
      ->execute();
    return;
  }

  // If the node we're deleting is the base of the series, then we'll need to
  // set a new series base on every node in the series.
  $series_base = $series_base == $deleted_nid ? $series_nodes['1']['nid'] : $series_base;
  foreach ($series_nodes as $series_node) {
    if ($series_node['weight'] <= $deleted_weight) {
      continue;
    }
    db_update('bgimage_series')
      ->fields(array('series' => $series_base, 'weight' => $series_node['weight'] - 1))
      ->condition('nid', $series_node['nid'])
      ->execute();
  }

  db_delete('bgimage_series')
    ->condition('nid', $deleted_nid)
    ->execute();
}

/**
 * Implements hook_filter_info().
 */
function bgimage_filter_info() {
  $filters['bg_thumb'] = array(
    'title' => t('Image thumb filter'),
    'description' => t('Changes the [:thumb] pseudo-BBCode tag into an image thumbnail.'),
    'process callback'  => '_bgimage_filter_thumb_process',
  );
  return $filters;
}

/**
 * [:thumb] filter callback.
 *
 * @param text $text
 * @return filtered text.
 */
function _bgimage_filter_thumb_process($text, $filter, $format) {
  // Extract all the nids referenced by [thumb:124], [thumb:83], etc.
  if (preg_match_all("/\[thumb:(\d+)\]/i", $text, $matches)) {
    $nids = $matches[1];
    
    // In $map, nid is the key and match occurrence number is the value.
    // Thus we have keys of every match:
    // array( 83 => 2, 124 => 1, ...)
    $map = array_flip($matches[1]);
    
    // Retrieve information about each nid.
    $result = db_query('SELECT n.nid, n.title, i.base
                        FROM {node} n, {bgimage} i
                        WHERE i.nid = n.nid AND n.nid IN (:nids)', array(':nids' => $nids));
    $expanded = array();
    $img = array();
    foreach ($result as $img) {
      // $n is the occurrence number
      $n = $map[$img->nid];
      $obfuscate = image_obfuscate($img->base . $img->nid);
      $prefix = bgimage_get_prefix($obfuscate);
      $uri = 'public://raw/' . $prefix . $obfuscate  .'.jpg';
      $rendered_image = theme('image_style', array('path' => $uri, 'style_name' => 'bg_small'));
      $expanded[$n] = '<a href="' . url('node/' . $img->nid) . '" title="' . check_plain($img->title) . '">' . $rendered_image  . '</a>';
    }

    // Create two arrays, $search and $replace, with corresponding
    // positional elements.
    foreach ($matches[1] as $key => $value) {
      //        [thumb:144595]
      $search[] = $matches[0][$key];
      //        <img src="https://bugguide.net/files/styles/bg_small/public/0L3/H0L/0L3H0LDHXL8RHZOZFL4L6ZQLPZLL6ZKL6Z8HVH5HVHZL6ZQLDHUHYH8LBZML1Z2HFH9HFHXLUZ6HFH9HZRNHRRGL9ZEHVHKL.jpg" alt="" />
      if (isset($expanded[$key])) {
        $replace[] = $expanded[$key];
      }
      else {
        // [thumb:55] references nid 55 but nid 55 was deleted.
        // Leave a hint in markup. TODO: make this survive later text filters.
        $replace[] = '<!--image ' . $value . ' deleted-->';
      }
    }
    $text = str_replace($search, $replace, $text);
  }
  return $text;
}

/**
 * Get a rendered thumbnail image.
 *
 * Example of a thumbnail image:
 * <img src="http://./files/styles/bg_small/public/108/K10/108K10LKZS3ROQHQYQY0BQY05Q10PQ9K5QC04QWKLK102QO04QA0LKB04QUKRKD00KDKWQVK9QB0UQB0GQF04QC05QC0.jpg?itok=QTeqhGF8" alt="" />
 *
 * @param stdclass $node
 *   The node object.
 *
 * @return string
 *   The rendered thumbnail image.
 *
 * @throws Exception
 */
function bgimage_thumb($node) {
  // e.g., for $node->nid = 1877
  // $base = 665891889baf9ad4d0cb1626a5f56fb5
  $base = $node->field_bgimage_base[LANGUAGE_NONE][0]['value'];

  // This is what legacy BugGuide used, before image styles:
  // $obfuscate = image_obfuscate($base . $node->nid . "?l=125");
  $obfuscate = image_obfuscate($base . $node->nid);
  $prefix = bgimage_get_prefix($obfuscate);
  // $uri = public://raw/MZA/LMZ/MZALMZWLLZELSRWLFL9LKRJZLZ6LYL9LRZJZHZ9L0R3Z3LDZGRTLERDLHZCLHZULXZ9LFLWLFL.jpg
  $uri = 'public://raw/' . $prefix . $obfuscate  .'.jpg';
  // <img src="http://./files/styles/bg_small/public/108/K10/108K10LKZS3ROQHQYQY0BQY05Q10PQ9K5QC04QWKLK102QO04QA0LKB04QUKRKD00KDKWQVK9QB0UQB0GQF04QC05QC0.jpg?itok=QTeqhGF8" alt="" />
  return theme('image_style', array(
    'path' => $uri,
    'style_name' => 'bg_small',
    'alt' => $node->title,
    'title' => $node->title,
  ));
}

/**
 * Get a thumbnail linkable image of node.
 *
 * @param stdclass $node
 *   The node object.
 * @return string
 *   A link with image as thumbnail else empty.
 */
function bgimage_thumb_link($node) {
  if (!$node) {
    return '';
  }
  return l(bgimage_thumb($node), 'node/' . $node->nid, array(
    'html' => TRUE,
    'attributes' => array(
      'title' => $node->title,
    ),
  ));
}

/**
 * Implements hook_field_widget_form_alter().
 */
function bgimage_preprocess_image_widget(&$variables) {
  // Removes the 'Upload' button and source image URL from the bgimage image field.
  if ($variables['element']['#field_name'] == 'field_bgimage_image') {
    $variables['element']['upload_button']['#access'] = FALSE;
    $variables['element']['filename']['#access'] = FALSE;
  }
}

/**
 * Generate a unique hash.
 *
 * @return string
 *   A string that will be placed in the field_data_field_bgimage_base field
 *   and the bgimage.base field. 
 */
function bgimage_generate_uuid() {
  $unique_base_created = FALSE;
  while (!$unique_base_created) {
    $uuid = md5(drupal_random_bytes(32));
    $already_exists = db_query("SELECT field_bgimage_base_value FROM {field_data_field_bgimage_base} WHERE field_bgimage_base_value = :uuid", array(':uuid' => $uuid))->fetchField();
    if ($already_exists) {
      watchdog('image', 'md5 hash collision, regenerating (' . $uuid . ')');      
    }
    else {
      $unique_base_created = TRUE;  
    }
  }
  return $uuid;
}

/**
 * Obfuscates an uploaded image for a bgimage node.
 *
 * @param object @node
 */
function _bgimage_obfuscate_uploaded_image(&$node) {
  // Even though the image field is required, during migration it may not be
  // present.
  if (isset($node->field_bgimage_image[LANGUAGE_NONE])) {
    $node->bgimage_uuid = bgimage_generate_uuid();
    $obfuscate = image_obfuscate($node->bgimage_uuid);
    $prefix = bgimage_get_prefix($obfuscate);
    $directory = 'public://raw/' . $prefix;
    if (!file_prepare_directory($directory, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
      watchdog('image', 'Failed to create style directory: %directory', array('%directory' => $directory), WATCHDOG_ERROR);
      return FALSE;
    }

    $file = file_load($node->{'field_bgimage_image'}[LANGUAGE_NONE][0]['fid']);
    // Move file into scalable file area, e.g.
    // files/raw/7H3/HEH/7H3HEHUZ6H3HMLUZ8LWZUHLRUHVZMLZR5LAZ8LUZ6HBH0L6Z4H6ZLLOHIHBHQL5Z8H.jpg
    file_move($file, $directory . $obfuscate . '.jpg');
  }
}

/**
 * Extracts data from a bgimage node to be stored in bgimage table.
 *
 * @param object @node
 *   A bgimage node.
 * @return array
 *   An array containing the data to be saved in the database.
 */
function _bgimage_prepare($node) {
  $wrapper = entity_metadata_wrapper('node', $node);

  $male = 0;
  $female = 0;
  foreach ($wrapper->field_bgimage_sex->value() as $selected_value) {
    if ($selected_value == 'female') {
      $female = 1;
    }
    elseif ($selected_value == 'male') {
      $male = 1;
    }
  }

  $egg = 0;
  $immature = 0;
  $pupa = 0;
  $adult = 0;
  foreach ($wrapper->field_bgimage_life_stage->value() as $selected_value) {
    if ($selected_value == 'immature') {
      $immature = 1;
    }
    elseif ($selected_value == 'adult') {
      $adult = 1;
    }
  }

  // Fetch image details.
  $width = 0;
  $height = 0;
  $filesize = 0;
  $image_data = $wrapper->field_bgimage_image->value();
  if (!empty($image_data)) {
    $width = $image_data['width'];
    $height = $image_data['height'];
    // Oopsie, the field does not store the filesize.
  }

  $fields = array(
    'nid' => $node->nid,
    'parent' => $wrapper->field_parent->value() ? $wrapper->field_parent->value() : 0,
    'parent_idx' => $wrapper->field_parent->value() . ',',
    'id' => $wrapper->field_bgimage_id->value(),
    'date_taken' => $wrapper->field_bgimage_date->value(),
    'width' => $width,
    'height' => $height,
    'filesize' => $filesize,
    'weight' => 0,
    'representative' => 0,
    'male' => $male,
    'female' => $female,
    'adult' => $adult,
    'immature' => $immature,
    'size' => $wrapper->field_bgimage_size->value(),
    'owner' => $wrapper->field_bgimage_copyright_owner->value(),
    'county' => $wrapper->field_bgimage_county->value(),
  );

  return $fields;
}

/**
 * Modify paths of derivative images.
 *
 * @param string $result
 *   $result = $scheme . '://styles/' . $style_name . '/' . $scheme . '/' . $path;
 * @param unknown_type $context
 *   $context = array(
 *     'style_name' => $style_name,
 *     'uri' => $uri,
 *     'scheme' => $scheme,
 *     'path' => $path,
 *   );
 */
function bgimage_image_style_path_alter(&$style_path, $context) {
  // Only modify path if a derivative of a raw image was requested, like
  // raw/ELI/RTZ/ELIRTZ8RTL8RZH4ROLXZALIZNLYLCZQRYZMRFZ0RCZIROZRZCLMZRH0RFZFL3ZRZOZ.jpg
  if (substr($context['path'], 0, 4) != 'raw/') {
    return;
  }

  $s = pathinfo($context['path'], PATHINFO_FILENAME);
  // 7H3HEHUZ6H3HMLUZ8LWZUHLRUHVZMLZR5LAZ8LUZ6HBH0L6Z4H6ZLLOHIHBHQL5Z8H

  $uuid = image_deobfuscate($s);
  // faed59f39f56052153b48643f20ee94e

  $path = image_obfuscate($uuid . ',' . $context['style_name']) . '.jpg';
  // NH8ZYZMZZHIZOZZRILVZQLVHQLEZSL1HXHCHIHYHNHAZ8LNZMLUZGLAZIL1Z2HAHMH2ZGLUZUH9Z2H1Z.jpg

  $prefix = bgimage_get_prefix($path);
  // NH8/ZYZ/

  $style_path = $context['scheme'] . '://styles/' . $context['style_name'] . '/' . $context['scheme'] . '/' . $prefix . $path;
  // public://styles/medium/public/NH8/ZYZ/NH8ZYZMZZHIZOZZRILVZQLVHQLEZSL1HXHCHIHYHNHAZ8LNZMLUZGLAZIL1Z2HAHMH2ZGLUZUH9Z2H1Z.jpg
}

/**
 * Given URI of a derivative, return URI of original.
 */
function bgimage_original_from_derivative_path($scheme, $target) {
  // Only attempt to get original URI for scalable targets like
  // NH8/ZYZ/NH8ZYZMZZHIZOZZRILVZQLVHQLEZSL1HXHCHIHYHNHAZ8LNZMLUZGLAZIL1Z2HAHMH2ZGLUZUH9Z2H1Z.jpg
  if (strlen($target) < 8 || $target[3] != '/' || $target[7] != '/') {
    // Stock Drupal image_uri.
    return $scheme . '://' . $target;
  }

  $s = pathinfo($target, PATHINFO_FILENAME);
  // NH8ZYZMZZHIZOZZRILVZQLVHQLEZSL1HXHCHIHYHNHAZ8LNZMLUZGLAZIL1Z2HAHMH2ZGLUZUH9Z2H1Z

  $info = image_deobfuscate($s);
  // faed59f39f56052153b48643f20ee94e,medium

  $parts = explode(',', $info);
  $uuid = array_shift($parts);
  // faed59f39f56052153b48643f20ee94e

  $obfuscated = image_obfuscate($uuid);
  // ELIRTZ8RTL8RZH4ROLXZALIZNLYLCZQRYZMRFZ0RCZIROZRZCLMZRH0RFZFL3ZRZOZ

  $prefix = bgimage_get_prefix($obfuscated);
  // ELI/RTZ/

  return $scheme . '://' . 'raw/' . $prefix . $obfuscated . '.jpg';
  // public://raw/ELI/RTZ/ELIRTZ8RTL8RZH4ROLXZALIZNLYLCZQRYZMRFZ0RCZIROZRZCLMZRH0RFZFL3ZRZOZ.jpg
}

/**
 * Implements hook_clone_node_alter().
 *
 * @param $node
 *   Reference to the fully loaded node object being saved (the clone) that
 *   can be altered as needed.
 * @param array $context
 *   An array of context describing the clone operation. The keys are:
 *   - 'method' : Can be either 'prepopulate' or 'save-edit'.
 *   - 'original_node' : The original fully loaded node object being cloned.
 *
 * @see clone_node_save()
 * @see drupal_alter()
 */
function bgimage_clone_node_alter(&$node, $context) {
  if ($context['method'] == 'prepopulate') {
    // Don't prepopulate the image field.
    $node->field_bgimage_image = array(LANGUAGE_NONE => array());
    // Remove "Clone of".
    $node->title = str_replace('Clone of ', '', $node->title);
    // Add the original nid in order to update bgimage_series.
    $base_nid = _bgimage_get_series_base($context['original_node']->nid);
    $node->original_nid = $base_nid ? $base_nid : $context['original_node']->nid;
  }
}

/**
 * Altered menu title callback for cloning a bgimage node.
 */
function _bgimage_clone_action_link_title($node) {
  // A hack to present a shorter title in contextual links.
  if (current_path() != 'node/' . $node->nid) {
    return t('Clone');
  }
  if (variable_get('clone_use_node_type_name', 0)) {
    return t('Clone this !type', array('!type' => drupal_strtolower(node_type_get_name($node))));
  }
  return t('Add image of this individual');
}

/**
 * Implements hook_clone_access_alter().
 *
 * @see clone_access_cloning()
 */
function bgimage_clone_access_alter(&$access, $node) {
  // So far clone_access_cloning() has checked permissions. Deny cloning on nodes that are not bgimage nodes.
  if ($node->type != 'bgimage') {
    $access = FALSE;
  }
}

/**
 * Menu callback. View all clipped images at regular size for comparison.
 * See preprocess function below.
 */
function bgimage_view_clipped() {
  return theme('photo_comparison');
}

/**
 * Implements hook_block_info().
 */
function bgimage_block_info() {
  $blocks['clipped_images'] = array(
     'info' => t('Image Clipboard'),
     'cache' => DRUPAL_NO_CACHE,
   );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * The changes in HTML and CSS are to allow for the bulma.io Panel Component
 * https://bulma.io/documentation/components/panel/
 */
function bgimage_block_view($delta = '') {
  if (empty($_SESSION['clipboard_images'])) {
    return array();
  }

  // We return images wrapped by divs, and the controls.
  global $user;
  $content = '';
  $nids = explode(',', $_SESSION['clipboard_images']);
  $clip_count = 0;
  $same_uid = TRUE;
  $nodes = node_load_multiple($nids);
  $content = '<ul class="item-list panel-block flex-wrap">';
  foreach ($nodes as $node) {
    // Check if all images belong to the same user.
    if ($user->uid != $node->uid) {
      $same_uid = FALSE;
    }

    // Render a thumbnail of the image.
    $rendered_image = theme('image_style', array('path' => $node->field_bgimage_image[LANGUAGE_NONE][0]['uri'], 'style_name' => 'bg_small'));
    $content .= '<li class="mb-2 mr-2">';
    $content .= '<a class="is-block" href="' . url('node/' . $node->nid) . '" title="' . check_plain($node->title) . '">' . $rendered_image  . '</a>';
    $content .= l(t('<span class="icon is-small"><span class="fa fa-times" aria-hidden="true"></span></span><span>Remove</span>'), 'bgimage/unclip/' . $node->nid, array(
      'attributes' => array(
        'title' => t('Remove this image from the clipboard'),
        'class' => 'clip-remove button is-small',
        ),
      'query' => array('destination' => current_path()),
      'html' => TRUE,
    ));
    $content .= '</li>';
    $clip_count++;
  }
  $content .= '</ul>';

  $links = array();
  if ($clip_count > 1) {
    $links[] = l(t('<span class="icon is-small"><span class="fa fa-times" aria-hidden="true"></span></span><span>Remove all</span>'), 'bgimage/unclip_all', array(
      'attributes' => array(
        'title' => t('Remove these images from the clipboard'),
        'class' => 'clip-remove-all button is-small mr-1 mb-1',
        ),
      'query' => array('destination' => current_path()),
      'html' => TRUE,
    ));
  }

  if ($same_uid || user_access('link all bgimages')) {
    $links[] = l(t('<span class="icon is-small"><span class="fa fa-link" aria-hidden="true"></span></span><span>Link</span>'), 'bgimage/link', array(
      'attributes' => array(
        'title' => t('Link together these images of the same specimen.'),
        'class' => 'clip-link button is-small mr-1 mb-1',
        ),
      'query' => array('destination' => current_path()),
      'html' => TRUE,
    ));
  }

  $current_menu_item = menu_get_item();
  if (!empty($current_menu_item) && $current_menu_item['path'] == "node/%/bgimage" && ($same_uid || user_access('move all bgimages'))) {
    $current_nid = (int) arg(1);
    $links[] = l(t('<span class="icon is-small"><span class="fa fa-long-arrow-right" aria-hidden="true"></span></span><span>Move'), 'bgimage/move/' . $current_nid, array(
      'attributes' => array(
        'title' => t('Move these images to the taxonomy of the current page.'),
        'class' => 'clip-move button is-small mr-1 mb-1',
        ),
      'html' => TRUE,
    ));
    if (user_access('quiet move all bgimages')) {
      $links[] = l(t('<span class="icon is-small"><span class="fa fa-long-arrow-right" aria-hidden="true"></span></span><span>Quiet move</span>'), 'bgimage/quiet_move/' . $current_nid, array(
        'attributes' => array(
          'title' => t('Quietly move these images to the taxonomy of the current page.'),
          'class' => 'clip-move button is-small mb-1',
          ),
        'html' => TRUE,
      ));
    }
  }

  $content .= '<div class="panel-block flex-wrap">'. implode(' ', $links) . '</div>';

  return array(
    'subject' => t('Clipboard'),
    'content' => $content,
  );
}

/**
 * Returns the base series nid (i.e. the first image in the series) for a given
 * nid.
 *
 * @param int $nid
 *   The nid of a node that belongs to a series.
 * return int|NULL
 *   The series nid if $nid belongs to a series, or NULL if not.
 */
function _bgimage_get_series_base($nid) {
  // First, check if there are related images.
  $result = db_query('SELECT series FROM {bgimage_series} WHERE nid = :nid', array(':nid' => $nid))->fetchAssoc();
  // fetchAssoc() returns FALSE if no results, otherwise an associative array.
  return $result ? $result['series'] : NULL;
}

/**
 * Returns a series of images given an nid.
 *
 * @param int $nid
 *   The nid of a node that belongs to the series.
 * return array|NULL
 *   An array of nids or NULL if the nid does not belong to a series.
 */
function bgimage_get_series($nid) {
  $series_base_nid = _bgimage_get_series_base($nid);
  if (!$series_base_nid) {
    return NULL;
  }

  // Next, extract the nids of all the images in the series.
  $nids = db_query('SELECT nid FROM {bgimage_series} WHERE series = :nid ORDER BY weight', array(':nid' => $series_base_nid))->fetchCol();

  return $nids;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Only allow users with Administer content permission to edit some fields.
 */
function bgimage_form_bgimage_node_form_alter(&$form, &$form_state) {
  if (!user_access('administer nodes')) {
    $form['field_parent']['#access'] = FALSE;
    $form['field_bgimage_base']['#access'] = FALSE;
  }
}

/**
 * Implements hook_views_pre_render().
 *
 * @param $view
 *   The view object.
 */
function bgimage_views_pre_render(&$view) {
  // For recent images views with display block show just 4 recent images
  // that doesn't contain ID Request as a parent.
  if (($view->name === 'recent_images') && ($view->current_display == 'block')) {
    $nids_not_in_id_request = 0;
    foreach ($view->result as $key => $record) {
      $node = node_load($record->nid);
      $parent_value = bg_get_first_parent_nid($node);
      if ($parent_value && $parent_value != BG_ID_REQUEST_NID && $nids_not_in_id_request < 4) {
        $series_base = _bgimage_get_series_base($record->nid);
        // (1) nid is not a member of a series and $series_base is NULL - keep
        // (2) nid is a member of the series and the series base - keep
        // (3) nid is a member of the series but not the series base - discard
        // To match (3) a result is present in $series_base and it is not the nid of the
        // record. Nest this if() so that series queries are only done on nids that have
        // passed the other tests.
        if ($series_base && $record->nid != $series_base) {
          unset($view->result[$key]);
          continue;
        }
        $nids_not_in_id_request++;
      }
      else {
        // Remove ID Request result.
        unset($view->result[$key]);
      }
    }
  }
}
