<?php

/**
 * Implements hook_menu().
 */
function bgmap_menu() {
  $items = array();

  $items['node/%node/bgmap'] = array(
    'title' => 'Data',
    'page callback' => 'bgmap_page',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'bgmap.pages.inc',
  );
  $items['node/%node/bgmap/json'] = array(
    'title' => 'Map',
    'page callback' => 'bgmap_json',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'bgmap.pages.inc',
  );
  $items['node/%node/bgmap/state/json'] = array(
    'title' => 'Map',
    'page callback' => 'bgmap_state_json',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'bgmap.pages.inc',
  );

  return $items;
}
