<?php
/**
 * @file
 * Code for the BG User Fields feature.
 */

include_once 'bguserfields.features.inc';

/**
 * Implements hook_menu_alter().
 */
function bguserfields_menu_alter(&$items) {
  $items["user/%user/track"]["title"] = t('Activity');
}

/**
 * Implements hook_ds_fields_info().
 */
function bguserfields_ds_fields_info($entity_type) {
  $fields = array();

  if ($entity_type == 'user') {
    $fields['bguserfields_contributed_images'] = array(
      'title' => t('Total contributed images'),
      'description' => t('Renders a link to contributed images by a user.'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => '_bguserfields_field_contributed_images',
      'file' => drupal_get_path('module', 'bguserfields') . '/bguserfields.ds.field.inc',
    );

    return array($entity_type => $fields);
  }
  return;
}

/**
 * Implements hook_views_pre_view().
 */
function bguserfields_views_pre_render($view) {
  // Sets a heading that links to the author at Contributed images view.
  if (($view->name == 'contributed_images') && ($view->current_display == 'page')) {
    if (isset($view->args[0])) {
      $user = user_load_by_name($view->args[0]);
      $user_wrapper = entity_metadata_wrapper('user', $user);
      $view->attachment_before = 'Contributed images by ' . l($user_wrapper->field_user_full_name->value(), 'user/' . $user->uid) . ':';
    }
  }
}

/**
 * Implements hook_user_view_alter().
 */
function bguserfields_user_view_alter(&$build) {
  if ($build['#view_mode'] != 'full') {
    return;
  }

  // Display the public email as a mailto: link (even though it may not be a
  // valid email address).
  if (isset($build['field_email'][0]['#markup'])) {
    $email = check_url($build['field_email'][0]['#markup']);
    $build['field_email'][0]['#markup'] = l($email, 'mailto:' . $email);
  }
}

/**
 * Returns the user's full name or its username.
 *
 * @param object $user_wrapper
 *   An EntityMetadataWrapper for the user.
 * @return
 *   String the user's full name or it's username.
 *   Empty string if the wrapper is empty.
 */
function bguserfields_get_name($user_wrapper) {
  $user_name = '';
  if ($user_wrapper) {
    $user_name = $user_wrapper->field_user_full_name->value();
    if (empty($user_name)) {
      $user_name = $user_wrapper->name->value();
    }
  }
  return $user_name;
}
