<?php

// Node ID of ID Request
define('BG_ID_REQUEST_NID', 6);

// Node ID of Frass
define('BG_FRASS_NID', 9410);

/**
 * @file
 * The plantguide module provides plantguide-specific functionality.
 */

/**
 * Implements hook_form_form_id_alter().
 *
 * Insert common name references for plants into common name field.
 */
function plantguide_form_bgpage_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_common_name'][LANGUAGE_NONE][0]['value']['#description'] = 'Try to find a unique common name. Otherwise use the scientific name for the taxon. If no common name is available for a species page, use the genus and species together, but do not capitalize the species. You can look up common names and scientific names at the <a href="http://plants.usda.gov/java/" target="_blank">USDA NRCS Name Search (opens in new window, search at upper left on page)</a>.';
}
