<?php

/**
 * @file
 * Hook implementations for bgapi module.
 */

include_once 'bgapi.features.inc';

/**
 * Implements hook_menu().
 */
function bgapi_menu() {
  
  $items['bgapi'] = array(
    'title' => 'Get tree',
    'description' => 'Default API page',
    'page callback' => 'bgapi_default',
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['bgapitree'] = array(
    'title' => 'Get tree',
    'description' => 'Get taxonomic tree',
    'page callback' => 'bgapi_get_tree',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'file' => 'bgapi.pages.inc',
  );
  $items['bgapitreevocab'] = array(
    'title' => 'Get tree',
    'description' => 'Get taxonomic tree',
    'page callback' => 'bgapi_get_tree_vocab',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'file' => 'bgapi.pages.inc',
  );
  
  return $items;
}

/**
 * A request for https://api.bugguide.net/foo.txt will be intercepted by Apache which will
 * attempt to serve the file out of bgapi/foo.txt if foo.txt exists. Note there is no
 * Drupal involvement in that situation.
 *
 * If the request is for https://api.bugguide.net/does/not/exist.txt the request will
 * be handled by Drupal in this function.
 *
 * Since nothing exists programmatically yet the user (or more likely, bot) is
 * redirected to the current doc page on how to use the API.
 */
function bgapi_default() {
  drupal_goto('https://bugguide.net/node/view/1401565');
}
