<?php

/**
 * @file
 * Hook implementations for bgapi module.
 */

include_once 'bgapi.features.inc';

/**
 * Implements hook_menu().
 */
function bgapi_menu() {
  
  $items['bgapi'] = array(
    'title' => 'Get tree',
    'description' => 'BugGuide system utilities',
    'page callback' => 'drupal_goto',
    'access arguments' => array('access content'),
    'page arguments' => array('https://bugguide.net/node/view/1401565'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['bgapitree'] = array(
    'title' => 'Get tree',
    'description' => 'Get taxonomic tree',
    'page callback' => 'bgapi_get_tree',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'file' => 'bgapi.pages.inc',
  );
  $items['bgapitreevocab'] = array(
    'title' => 'Get tree',
    'description' => 'Get taxonomic tree',
    'page callback' => 'bgapi_get_tree_vocab',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'file' => 'bgapi.pages.inc',
  );
  
  return $items;
}
