<?php
/**
 * @file
 * Code for the BugGuide book references feature.
 */

include_once 'bgref.features.inc';

function bgref_views_query_alter(&$view, &$query) {
  // Transform bgpage nid that comes as an argument into its parents field.
  if (($view->name === 'all_books') && ($view->current_display == 'by_bgpage')) {
    $bgpage = node_load($view->args[0]);
    $parents = $bgpage->nid;
    if (!empty($bgpage->field_parent['und'][0]['value'])) {
      $parents = $bgpage->field_parent['und'][0]['value'] . ',' . $bgpage->nid;
    }
    $query->where[1]['conditions'][2]['value'] = $parents . '%';
  }
}
